job('TestDSLJob') {
    description("First job generated by the DSL on ${new Date()}, the project is a test project hosted on github")
    scm {
        git("https://github.com/rahul-yadav-hub/Jenkins.git", 'main')
    }
    triggers {
        scm('* 5 * * *')
    }
    steps {
        shell('echo Hello World!')
    }
}
